//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> "if"
 * f2 -> Expression()
 * f3 -> Expression()
 * f4 -> Expression()
 * f5 -> ")"
 */
public class IfExpression implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Expression f2;
   public Expression f3;
   public Expression f4;
   public NodeToken f5;

   public IfExpression(NodeToken n0, NodeToken n1, Expression n2, Expression n3, Expression n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public IfExpression(Expression n0, Expression n1, Expression n2) {
      f0 = new NodeToken("(");
      f1 = new NodeToken("if");
      f2 = n0;
      f3 = n1;
      f4 = n2;
      f5 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

